package tdg.game.stats;

public enum Leagues
{
	BRONZE5, BRONZE4, BRONZE3, BRONZE2, BRONZE1,
	SILVER5, SILVER4, SILVER3, SILVER2, SILVER1,
	GOLD5, GOLD4, GOLD3, GOLD2, GOLD1,
	PLATINUM5, PLATINUM4, PLATINUM3, PLATINUM2, PLATINUM1,
	DIAMOND5, DIAMOND4, DIAMOND3, DIAMOND2, DIAMOND1,
	MASTER5, MASTER4, MASTER3, MASTER2, MASTER1,
	LEGEND3, LEGEND2, LEGEND1,
	DIVINE3, DIVINE2, DIVINE1,
	CREATOR;
}
